def get_preamble():

    preamble = []
    preamble.append('IMPORTANT:')
    preamble.append('-------------------------------------------------------------------------')
    preamble.append('This email has been auto-generated by the VICOROB XNAT research plattform.')
    preamble.append('The VICOROB XNAT research plattform is a research tool, do not use for diagnostic purposes.')
    preamble.append(' ')
    preamble.append('Computer Vision and Robotics Institute (VICOROB)')
    preamble.append('https://vicorob.udg.edu')
    preamble.append('University of Girona, 2020')
    preamble.append('-------------------------------------------------------------------------')
    preamble.append(' ')

    return preamble
